version: "3.4"
services:
  weddingdb:
    image: postgis/postgis
    environment:
      - "POSTGRES_USER=wedding-qr"
      - "POSTGRES_PASSWORD=wedding-qr"
      - "POSTGRES_DB=wedding-service"
    volumes:
      - weddingdb-data:/var/lib/postgresql/data
      # - ./create_test_db.sh:/docker-entrypoint-initdb.d/create_test_db.sh
    ports:
      - 5432:5432
  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
  api-gateway:
    build:
      context: ./api
      dockerfile: build/local/Dockerfile.local
    ports:
      - 9000:9000
      - 2345:2345
    volumes:
      - "./api:/build/"
    command: "make run"
  wedding-service:
    build:
      context: ./wedding
      dockerfile: build/local/Dockerfile.local
    volumes:
      - "./wedding:/build/"
    command: "make run"
  user-service:
    build:
      context: ./users
      dockerfile: build/local/Dockerfile.local
    volumes:
      - "./users:/build/"
    command: "make run"
volumes:
  weddingdb-data:
