// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Invitation struct {
	ID        uuid.UUID
	Invitees  string
	Status    int64
	CreatedAt sql.NullTime
	WeddingID uuid.UUID
}

type Wedding struct {
	ID          uuid.UUID
	Names       string
	Status      int64
	UserID      uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	WeddingDate time.Time
}
