// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: proto/getWedding.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Invitation_Status int32

const (
	Invitation_Pending      Invitation_Status = 0
	Invitation_Attending    Invitation_Status = 1
	Invitation_NotAttending Invitation_Status = 2
)

// Enum value maps for Invitation_Status.
var (
	Invitation_Status_name = map[int32]string{
		0: "Pending",
		1: "Attending",
		2: "NotAttending",
	}
	Invitation_Status_value = map[string]int32{
		"Pending":      0,
		"Attending":    1,
		"NotAttending": 2,
	}
)

func (x Invitation_Status) Enum() *Invitation_Status {
	p := new(Invitation_Status)
	*p = x
	return p
}

func (x Invitation_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Invitation_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_getWedding_proto_enumTypes[0].Descriptor()
}

func (Invitation_Status) Type() protoreflect.EnumType {
	return &file_proto_getWedding_proto_enumTypes[0]
}

func (x Invitation_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Invitation_Status.Descriptor instead.
func (Invitation_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_getWedding_proto_rawDescGZIP(), []int{2, 0}
}

type WeddingResponse_Type int32

const (
	WeddingResponse_Error   WeddingResponse_Type = 0
	WeddingResponse_Success WeddingResponse_Type = 1
)

// Enum value maps for WeddingResponse_Type.
var (
	WeddingResponse_Type_name = map[int32]string{
		0: "Error",
		1: "Success",
	}
	WeddingResponse_Type_value = map[string]int32{
		"Error":   0,
		"Success": 1,
	}
)

func (x WeddingResponse_Type) Enum() *WeddingResponse_Type {
	p := new(WeddingResponse_Type)
	*p = x
	return p
}

func (x WeddingResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeddingResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_getWedding_proto_enumTypes[1].Descriptor()
}

func (WeddingResponse_Type) Type() protoreflect.EnumType {
	return &file_proto_getWedding_proto_enumTypes[1]
}

func (x WeddingResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeddingResponse_Type.Descriptor instead.
func (WeddingResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_getWedding_proto_rawDescGZIP(), []int{3, 0}
}

type GetWedding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *GetWedding) Reset() {
	*x = GetWedding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_getWedding_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWedding) ProtoMessage() {}

func (x *GetWedding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getWedding_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWedding.ProtoReflect.Descriptor instead.
func (*GetWedding) Descriptor() ([]byte, []int) {
	return file_proto_getWedding_proto_rawDescGZIP(), []int{0}
}

func (x *GetWedding) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Wedding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid        string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Names       string                 `protobuf:"bytes,2,opt,name=names,proto3" json:"names,omitempty"`
	WeddingDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=weddingDate,proto3" json:"weddingDate,omitempty"`
	Invitations []*Invitation          `protobuf:"bytes,5,rep,name=invitations,proto3" json:"invitations,omitempty"`
}

func (x *Wedding) Reset() {
	*x = Wedding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_getWedding_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wedding) ProtoMessage() {}

func (x *Wedding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getWedding_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wedding.ProtoReflect.Descriptor instead.
func (*Wedding) Descriptor() ([]byte, []int) {
	return file_proto_getWedding_proto_rawDescGZIP(), []int{1}
}

func (x *Wedding) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Wedding) GetNames() string {
	if x != nil {
		return x.Names
	}
	return ""
}

func (x *Wedding) GetWeddingDate() *timestamppb.Timestamp {
	if x != nil {
		return x.WeddingDate
	}
	return nil
}

func (x *Wedding) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

type Invitation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid   string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Names  string            `protobuf:"bytes,2,opt,name=names,proto3" json:"names,omitempty"`
	Status Invitation_Status `protobuf:"varint,3,opt,name=status,proto3,enum=wedding.Invitation_Status" json:"status,omitempty"`
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_getWedding_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getWedding_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_proto_getWedding_proto_rawDescGZIP(), []int{2}
}

func (x *Invitation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Invitation) GetNames() string {
	if x != nil {
		return x.Names
	}
	return ""
}

func (x *Invitation) GetStatus() Invitation_Status {
	if x != nil {
		return x.Status
	}
	return Invitation_Pending
}

type WeddingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      WeddingResponse_Type `protobuf:"varint,1,opt,name=type,proto3,enum=wedding.WeddingResponse_Type" json:"type,omitempty"`
	Wedding   *Wedding             `protobuf:"bytes,2,opt,name=wedding,proto3" json:"wedding,omitempty"`
	ErrorCode int32                `protobuf:"varint,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
}

func (x *WeddingResponse) Reset() {
	*x = WeddingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_getWedding_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeddingResponse) ProtoMessage() {}

func (x *WeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_getWedding_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeddingResponse.ProtoReflect.Descriptor instead.
func (*WeddingResponse) Descriptor() ([]byte, []int) {
	return file_proto_getWedding_proto_rawDescGZIP(), []int{3}
}

func (x *WeddingResponse) GetType() WeddingResponse_Type {
	if x != nil {
		return x.Type
	}
	return WeddingResponse_Error
}

func (x *WeddingResponse) GetWedding() *Wedding {
	if x != nil {
		return x.Wedding
	}
	return nil
}

func (x *WeddingResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

var File_proto_getWedding_proto protoreflect.FileDescriptor

var file_proto_getWedding_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x74, 0x57, 0x65, 0x64, 0x64, 0x69,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x77, 0x65, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x20, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x57, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x22, 0xa8, 0x01, 0x0a, 0x07, 0x57, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0b, 0x77, 0x65,
	0x64, 0x64, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x77, 0x65, 0x64,
	0x64, 0x69, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x77, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0xa2, 0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x77, 0x65, 0x64, 0x64, 0x69,
	0x6e, 0x67, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x36, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x6f, 0x74, 0x41, 0x74, 0x74, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x10, 0x02, 0x22, 0xae, 0x01, 0x0a, 0x0f, 0x57, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x77, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x2e, 0x57, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x77,
	0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x77,
	0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x57, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x07,
	0x77, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x1e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x10, 0x01, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_getWedding_proto_rawDescOnce sync.Once
	file_proto_getWedding_proto_rawDescData = file_proto_getWedding_proto_rawDesc
)

func file_proto_getWedding_proto_rawDescGZIP() []byte {
	file_proto_getWedding_proto_rawDescOnce.Do(func() {
		file_proto_getWedding_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_getWedding_proto_rawDescData)
	})
	return file_proto_getWedding_proto_rawDescData
}

var file_proto_getWedding_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_getWedding_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_getWedding_proto_goTypes = []interface{}{
	(Invitation_Status)(0),        // 0: wedding.Invitation.Status
	(WeddingResponse_Type)(0),     // 1: wedding.WeddingResponse.Type
	(*GetWedding)(nil),            // 2: wedding.GetWedding
	(*Wedding)(nil),               // 3: wedding.Wedding
	(*Invitation)(nil),            // 4: wedding.Invitation
	(*WeddingResponse)(nil),       // 5: wedding.WeddingResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_getWedding_proto_depIdxs = []int32{
	6, // 0: wedding.Wedding.weddingDate:type_name -> google.protobuf.Timestamp
	4, // 1: wedding.Wedding.invitations:type_name -> wedding.Invitation
	0, // 2: wedding.Invitation.status:type_name -> wedding.Invitation.Status
	1, // 3: wedding.WeddingResponse.type:type_name -> wedding.WeddingResponse.Type
	3, // 4: wedding.WeddingResponse.wedding:type_name -> wedding.Wedding
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_getWedding_proto_init() }
func file_proto_getWedding_proto_init() {
	if File_proto_getWedding_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_getWedding_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWedding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_getWedding_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wedding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_getWedding_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Invitation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_getWedding_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeddingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_getWedding_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_getWedding_proto_goTypes,
		DependencyIndexes: file_proto_getWedding_proto_depIdxs,
		EnumInfos:         file_proto_getWedding_proto_enumTypes,
		MessageInfos:      file_proto_getWedding_proto_msgTypes,
	}.Build()
	File_proto_getWedding_proto = out.File
	file_proto_getWedding_proto_rawDesc = nil
	file_proto_getWedding_proto_goTypes = nil
	file_proto_getWedding_proto_depIdxs = nil
}
